keys:
  - &lawrence dc78ffa471a243a8a629d54b2a0c2fb492f5fa27
  - &flaky age1rm589yj8xa7r4uh802ru96ypsrllze6q0rh8ax4uryr70c7nt90quwxa39
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *lawrence
      age:
      - *flaky
